[theme]
base = "dark"
primaryColor = "#2b8bd8"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#161b22"
textColor = "#f0f2f6"
font = "sans serif"

[server]
headless = true
maxUploadSize = 100
