from html import escape


def build_report(a):
    detected = a.get("detected", {})
    detected_rows = "".join(
        f"<tr><td>{escape(str(k))}</td><td>{escape(str(v))}</td></tr>"
        for k, v in detected.items()
        if k != "dimensions"
    )

    issue_rows = "".join(
        f"<tr><td>{escape(i['priority'])}</td>"
        f"<td>{escape(i['title'])}</td>"
        f"<td>{escape(i['observed'])}</td>"
        f"<td>{escape(i['problem'])}</td>"
        f"<td>{escape(i['recommendation'])}</td></tr>"
        for i in a["issues"]
    )

    html = f"""<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>MechForge AI DFM Report</title>
<style>
body{{font-family:Arial,sans-serif;margin:40px;color:#17202a;line-height:1.45}}
h1{{margin-bottom:4px}} h2{{margin-top:28px}}
.score{{font-size:42px;font-weight:bold}}
table{{border-collapse:collapse;width:100%;margin-top:10px}}
td,th{{border:1px solid #bbb;padding:8px;text-align:left;vertical-align:top}}
th{{background:#f2f4f6}}
.note{{padding:12px;border:1px solid #ccc;border-radius:8px}}
</style>
</head>
<body>
<h1>MechForge AI — DFM Report</h1>
<p><b>Project:</b> {escape(a['project'])}<br>
<b>Component:</b> {escape(a['component'])}<br>
<b>Material:</b> {escape(a['material'])}<br>
<b>Process:</b> {escape(a['recommended_process'])}</p>

<div class="score">{a['score']}/100</div>
<p>Manufacturability: <b>{escape(a['classification'])}</b></p>

<h2>Score Breakdown</h2>
<table>
<tr><th>Category</th><th>Score</th></tr>
{''.join(f"<tr><td>{escape(k)}</td><td>{v}/100</td></tr>" for k,v in a['breakdown'].items())}
</table>

<h2>Detected Drawing Data</h2>
<table><tr><th>Parameter</th><th>Value</th></tr>
{detected_rows or "<tr><td colspan='2'>No drawing values were extracted.</td></tr>"}
</table>

<h2>Economics</h2>
<p>Estimated unit cost: ₹{a['unit_low']:,.0f}–₹{a['unit_high']:,.0f}<br>
Estimated batch: ₹{a['batch_low']:,.0f}–₹{a['batch_high']:,.0f}<br>
Estimated machining time: {a['minutes']:.1f} min/component<br>
Quantity: {int(a['quantity']):,}</p>

<h2>Engineering Findings</h2>
<table>
<tr><th>Priority</th><th>Issue</th><th>Observed</th><th>Problem</th><th>Recommendation</th></tr>
{issue_rows}
</table>

<div class="note">
<b>Important:</b> These results are generated by a transparent prototype rules engine.
They are engineering decision-support estimates, not certification or a supplier quotation.
Verify drawing dimensions, GD&T, tooling, machine capability, material condition and cost
with a qualified design/manufacturing engineer before production.
</div>
</body>
</html>"""
    return html.encode("utf-8")
